### ISSUE TITLE
Version of psycopg2-binary

### ISSUE THREAD

**Issue by JavierArredondo** [alercebroker/ztf-api#30]
Error when I build the image:

```
ERROR: Cannot install -r requirements.txt (line 7) and psycopg2-binary==2.8.3 because these package versions have conflicting dependencies.
```

Solution: Change version in requirements.txt to  psycopg2-binary==2.8.6

**Comment by cvalenzu** [comment]
Error from db-plugins not this repository

**Comment by cvalenzu** [comment]
Already fixed
https://github.com/alercebroker/db-plugins/blob/76e5cb318ff8d0b500e2bc64a293069059d8ed35/requirements.txt#L6
